apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-db
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.externalDatabase.password | b64enc | quote }}