apiVersion: v1
kind: Pod
metadata:
  name: mysql-test
  namespace: wordpress
spec:
  containers:
  - name: mysql-client
    image: mysql:8.0
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    env:
    - name: MYSQL_PWD
       value: "Demo123!"
  restartPolicy: Never