# values.yaml
wordpress:
  wordpressUsername: admin
  wordpressPassword: mypassword123
  wordpressBlogName: "Franklynux WordPress Blog"
  wordpressEmail: chiwando3@outlook.com
  
  service:
    type: LoadBalancer
    port: 80
  
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi
  
  mariadb:
    enabled: false
  
  externalDatabase:
    host: 'database-wordpress.cs784686qxm6.us-east-1.rds.amazonaws.com'
    port: 3306
    user: Franklynux
    password: Admin123!
    database: wordpress
    existingSecret: "{{ include \"wordpress.fullname\" . }}-db"
    existingSecretPasswordKey: "mysql-password"
  
  ingress:
    enabled: false
    ingressClassName: nginx
    hostname: wordpress.local