apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        if obj.status.health.status == "Healthy" then
          hs.status = "Healthy"
        elseif obj.status.health.status == "Progressing" then
          hs.status = "Progressing"
        else
          hs.status = "Degraded"
        end
        return hs
    