apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: wordpress-git:/PersistentVolumeClaim:wordpress/wordpress-git
  labels:
    app.kubernetes.io/instance: wordpress-git
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.8.2
    helm.sh/chart: wordpress-25.0.3
  name: wordpress-git
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
