apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-git
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    chart: wordpress
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: mypassword123
        wordpressBlogName: "Franklynux WordPress Blog"
        wordpressEmail: chiwando3@outlook.com
        service:
          type: LoadBalancer
        persistence:
          enabled: true
          size: 10Gi
          storageClass: gp2
        mariadb:
          enabled: false
        externalDatabase:
          host: database-wordpress.cs784686qxm6.us-east-1.rds.amazonaws.com
          port: 3306
          user: Franklynux
          password: Admin123!
          database: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true