apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-git
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    chart: wordpress
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: mypassword123
        wordpressBlogName: "Franklynux WordPress Blog"
        wordpressEmail: chiwando3@outlook.com
        service:
          type: LoadBalancer
        replicas: 2  
        persistence:
          enabled: true
          size: 10Gi
          storageClass: ebs-csi
        mariadb:
          enabled: false
        externalDatabase:
          host: wordpress-db.cs784686qxm6.us-east-1.rds.amazonaws.com
          port: 3306
          user: admin
          password: Demo123!
          database: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true